name: Icarus Verilog Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  # Manual Dispatch
  workflow_dispatch:  # Enables a manual trigger

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Icarus Verilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Compile Verilog Files
        run: |
          iverilog -o tests/test_output.vvp src/*.v tests/*.v 

      - name: Run Simulation
        run: |
          vvp tests/test_output.vvp | tee test_results.log

      - name: Check for Failure
        run: |
          set -e # forces the script to exit if any command fails
          if grep -q "ASSERTION FAILED" test_results.log; then
            echo "❌ Test failed: Found failure indicators in output"
            exit 1
          else
            echo "Test Passed"
          fi

